/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 23
#define YY_END_OF_BUFFER 24
static yyconst short int yy_accept[228] =
    {   0,
        0,    0,   24,   23,   23,   23,   23,   23,   14,   15,
       12,   12,   18,   12,   12,    7,   19,   11,   13,   11,
        9,    9,   20,   21,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
       16,   17,    0,    5,   11,    0,   10,    9,    0,    0,
        9,   12,    0,    1,    0,    0,    0,    8,    7,    6,
       11,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    4,    9,    9,    9,    9,    9,
        9,    4,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    0,   22,    9,    0,    0,    9,    9,

        0,    1,    0,    6,    0,    0,    6,    8,    6,    6,
        6,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    4,    9,    3,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    0,    9,    0,    0,    0,    0,    0,    2,    6,
        0,    0,    6,    6,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    3,    9,    9,    0,    0,    0,
        9,    0,    0,    2,    0,    6,    0,    0,    0,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,

        9,    9,    9,    9,    9,    0,    0,    0,    0,    0,
        6,    0,    0,    3,    9,    9,    9,    9,    9,    9,
        0,    0,    9,    9,    9,    9,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    6,    1,    1,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,    1,   17,   18,
       19,   20,    1,    1,   21,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   21,   23,   22,   22,   22,   22,   22,   21,   22,
       24,    1,   25,   26,    1,    1,   27,   28,   29,   30,

       31,   32,   33,   34,   35,   22,   36,   37,   38,   39,
       40,   41,   22,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   51,    1,   52,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[53] =
    {   0,
        1,    2,    3,    1,    1,    1,    4,    5,    6,    7,
        8,    1,    8,    4,    8,    9,    1,    1,    1,    1,
       10,   10,   10,    1,    1,    1,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       11,   11
    } ;

static yyconst short int yy_base[254] =
    {   0,
        0,    0,  395, 1080,  358,  357,  369,    0, 1080, 1080,
       50,  356, 1080,  353,   52,   49, 1080,   41,  346,  315,
       34,   36, 1080, 1080,   45,   47,   99,   42,   44,  131,
      133,  126,  129,  130,   43,  146,  140,  160,  155,  167,
      153, 1080,  305,  302, 1080,  307,  275,    0,   64,  274,
      265, 1080,  258, 1080,   91,    0,   67,  242,  201,  151,
      229,  175,  188,  191,  193,  202,  199,  194,  197,  198,
      221,  225,  236,  235,  236,  239,  244,  256,  251,  253,
      264,  259,  267,  279,  276,  289,  293,  296,  300,  309,
      319,  321,  328,  331,  362,    0,  244,  381,  233,  230,

      176,  219,  322,    0,  328,  219,  210,  161,  318,  334,
      347,  354,  360,  350,  376,  381,  390,  391,  392,  408,
      409,  410,  401,  406,  419,  411,  427,  434,  442,  447,
      425,  444,  453,  457,  459,  469,  439,  479,  486,  491,
      480,  536, 1080,  545,  554,  563,  165,  394,  172,    0,
      159,  572,  156,   88,  501,  541,  557,  501,  562,  571,
      572,  565,  579,  573,  569,  597,  583,  605,  608,  612,
      615,  621,  631,  605,  625,  631,  647,  207,  676,  691,
     1080,  700,    0, 1080,  709, 1080,  718,  727,  736,  629,
      714,  723,  728,  731,  723,  740,  743,  745,  751,  674,

      755,  735,  757,  771,  769,  289,  384,  453,  813,  822,
     1080,  831,    0,  761,  809,  811,  808,  829,  831,  763,
      479,  520,  836,  827,  855,  835, 1080,  895,  906,   69,
      915,  925,  933,  935,  938,  946,  954,  964,   67,  973,
      975,  984,  994,  997, 1005, 1013, 1021, 1029, 1037, 1045,
     1053, 1061, 1069
    } ;

static yyconst short int yy_def[254] =
    {   0,
      227,    1,  227,  227,  228,  227,  229,  230,  227,  227,
      231,  227,  227,  227,  232,  233,  227,  228,  227,  227,
      234,  234,  227,  227,  234,  234,  227,   27,   27,  234,
      234,   27,   27,   27,  234,  234,  234,   27,  234,  234,
      227,  227,  228,  228,  227,  229,  229,  235,  231,  236,
      237,  227,  232,  227,  238,  239,  240,  227,  233,  241,
      228,  234,  234,  227,  234,  234,  234,   27,   27,   27,
       27,   27,  228,   27,   27,   27,   27,   27,  234,  234,
      234,   27,   27,   27,  234,  234,  234,  234,  234,  234,
       27,  234,  234,  227,  227,  235,  236,  242,  227,  237,

      238,  243,  238,  244,  240,  245,  246,  227,  241,  241,
      227,  234,  234,  234,   27,   27,   27,   27,   27,   27,
       27,   27,  234,  234,  234,   27,   27,  234,  234,  234,
      234,  234,  234,  234,  234,  234,   27,   27,  234,  234,
      234,  247,  227,  247,  242,  248,  243,  243,  232,  244,
      245,  249,  227,  246,  234,  234,   27,   27,   27,   27,
       27,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,   27,   27,  234,  234,  234,  250,  247,  247,
      227,  248,  182,  227,  251,  227,  251,  249,  252,  234,
       27,   27,   27,   27,  234,  234,  234,  234,  234,  234,

      234,  234,  234,   27,  234,  227,  250,  253,  251,  251,
      227,  252,  212,  234,   27,   27,  234,  234,   27,  234,
      227,  253,   27,  234,   27,  234,    0,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227
    } ;

static yyconst short int yy_nxt[1133] =
    {   0,
        4,    4,    5,    6,    7,    5,    8,    9,   10,   11,
       12,   13,   14,    4,   15,   16,   17,   18,   19,   20,
       21,   21,   22,   23,   24,    4,   25,   26,   27,   28,
       29,   30,   31,   21,   32,   21,   33,   21,   34,   21,
       21,   35,   36,   37,   38,   39,   40,   21,   21,   21,
       41,   42,   49,   54,   63,   56,   63,   50,   57,   61,
       44,   55,   58,   63,   59,   63,   49,   63,   68,  105,
       68,   50,   74,   85,  106,   68,  104,   68,   48,   65,
       76,   75,   77,   68,   64,   64,   64,   64,   67,   66,
      153,   78,  102,   64,   64,   64,   64,   64,   64,   43,

      103,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   68,   43,   43,   43,   44,   69,
       68,   68,   43,   43,   43,   70,   68,   68,   68,   68,
       68,   68,   71,   68,   68,   68,   68,   68,   72,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   73,
       73,   63,   68,   63,   94,   68,   68,   82,  153,   68,
       63,  151,   68,   68,   83,   68,   63,   79,   84,   68,
       80,  110,   81,   54,  148,   63,  108,  102,   94,   86,
       87,   64,   64,   64,   64,  103,   68,   63,   90,   88,
       64,   64,   89,   68,   92,   63,   64,   64,   91,   68,

       93,  111,  111,   94,   95,   64,   64,   56,   63,  206,
       57,   64,  153,   63,  227,  143,   59,   64,   64,   63,
       68,  151,   63,   68,   68,   64,   64,   68,  148,  114,
       68,   68,   99,   68,  112,   99,   68,   68,   64,   64,
      115,   64,   64,   64,   64,  113,   97,  116,   44,   64,
       64,   68,   64,   64,   68,   44,   73,  108,   68,   54,
       68,   68,   68,  117,   68,   68,  118,   99,   68,   68,
       68,   63,   68,   63,   68,   68,   97,   68,   68,   47,
      119,  120,   68,   68,   63,   68,   73,   73,  121,   68,
      123,  206,   68,   68,  124,   68,   63,  143,   68,  122,

       68,   64,   64,   64,   64,   68,   68,  125,  128,   63,
      126,   47,   68,   63,   64,   64,   63,  127,   68,  129,
       63,   44,  133,  102,   44,  131,   64,   64,  130,   63,
      105,  103,   94,   45,  135,  106,  149,  134,  110,   64,
       64,   63,  132,   64,   64,   68,   64,   64,   63,  136,
       64,   64,   68,  137,  110,  139,   94,  140,   68,   64,
       64,  138,  141,   94,   45,   52,   52,  111,  111,  111,
       63,   64,   64,   47,   63,   45,  156,   44,   64,   64,
       63,   94,   95,  142,  111,  111,  206,   94,  155,  143,
      144,  144,  143,  144,  227,  144,  145,  111,  111,  124,

       64,   64,   68,  148,   64,   64,   82,   68,  184,   68,
       64,   64,   94,   95,   68,   68,   68,  159,   68,  160,
       68,   63,  126,   68,   68,   68,   63,  162,  227,   68,
       68,   68,  157,  158,   68,   68,   68,   68,   82,   63,
      161,   68,   68,   68,   68,   63,   82,   68,   68,   68,
       68,   64,   64,   68,   63,  221,   64,   64,  124,   82,
       68,  186,   63,  166,   63,   68,   68,   63,  163,   64,
       64,  227,   68,   63,  167,   64,   64,   63,  173,   63,
      227,  221,  227,  227,   64,   64,  164,  186,  165,   63,
      227,  169,   64,   64,   64,   64,  168,   64,   64,  172,

       63,  170,  171,   64,   64,   68,   63,   64,   64,   64,
       64,   63,   68,  174,  227,  175,  177,  176,   68,   64,
       64,   63,  221,  227,  227,  227,  227,   68,  186,  227,
       64,   64,  227,  227,   68,  191,   64,   64,  142,  190,
       68,   64,   64,  227,  143,  144,  144,  179,  144,  227,
      144,   64,   64,  227,  144,  144,  142,  144,  227,  144,
      227,   63,  143,  144,  144,  180,  144,  227,  144,  145,
      227,  181,  144,  144,  185,  144,  124,  144,  182,  227,
      186,  187,  187,   68,  187,   63,  187,  188,   68,   63,
       68,   64,   64,   63,  227,   68,   68,   68,   68,   63,

       82,   68,  227,   63,   68,   68,  192,  193,  175,  227,
       68,   68,  124,  194,  196,   64,   64,   63,  227,   64,
       64,  195,  198,   64,   64,   63,  227,  197,   63,   64,
       64,   68,   63,   64,   64,   63,  227,  204,   68,  199,
      201,   63,  227,  202,   68,   63,  200,   64,   64,   63,
      203,   63,  227,  227,  227,   64,   64,   68,   64,   64,
      227,  214,   64,   64,   68,   64,   64,   63,  227,   82,
       68,   64,   64,  227,  205,   64,   64,  124,  179,   64,
       64,   64,   64,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  180,   63,  227,  227,   64,   64,  181,

      144,  144,  180,  144,  227,  144,  175,  227,  181,  144,
      144,  185,  144,  227,  144,  182,  227,  186,  187,  187,
      209,  187,  227,  187,   64,   64,  227,  187,  187,  185,
      187,  227,  187,  227,  227,  186,  187,  187,  210,  187,
       68,  187,  188,   63,  211,  187,  187,   68,  187,   68,
      187,  212,  215,   68,   68,   63,   68,   68,  126,  216,
       63,   68,   68,   63,   68,   63,  217,   68,  124,   82,
       68,   63,  124,   64,   64,   63,  124,   63,  124,  124,
      227,   63,  227,   63,  227,   64,   64,  218,  227,   63,
       64,   64,  227,   64,   64,   64,   64,   68,  124,  226,

      227,   64,   64,  220,   68,   64,   64,   64,   64,  219,
       68,   64,   64,   64,   64,  209,  227,  227,  227,   64,
       64,  227,  227,  227,  210,  227,  227,  227,   63,  227,
      211,  187,  187,  210,  187,   68,  187,   68,  224,  211,
      187,  187,   68,  187,   68,  187,  212,   63,   68,   63,
       68,  227,  227,  223,   82,   63,  227,   68,   64,   64,
      124,  225,   68,  227,   68,  124,   82,  227,  124,   68,
       68,  227,  227,  227,  227,   68,  227,   64,   64,   64,
       64,   68,  227,  227,   82,   64,   64,  227,   68,  227,
      227,  227,  227,  227,   68,   43,  227,   43,   43,   43,

       43,   43,   43,   43,   43,   43,   46,  227,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   51,  227,   51,
      227,  227,  227,  227,   51,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   60,  227,  227,   60,
      227,   60,   60,   62,   62,   62,   96,   96,   98,  227,
      227,  227,  227,  227,  227,   98,  100,  227,  227,  227,
      227,  227,  100,  100,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  107,  227,  107,  227,  227,
      227,  227,  107,  109,  109,  109,  146,  227,  227,  146,
      146,  146,  146,  146,  147,  147,  147,  147,  147,  147,

      147,  147,  147,  147,  147,  150,  150,  152,  227,  227,
      227,  227,  227,  227,  152,  154,  227,  227,  227,  227,
      227,  154,  154,  178,  227,  227,  178,  178,  178,  227,
      178,  183,  227,  227,  183,  183,  183,  183,  183,  189,
      227,  227,  189,  189,  189,  189,  189,  207,  227,  227,
      207,  227,  227,  207,  207,  208,  227,  227,  208,  208,
      208,  227,  208,  213,  227,  227,  213,  213,  213,  213,
      213,  222,  227,  227,  222,  227,  227,  222,  222,    3,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,

      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227
    } ;

static yyconst short int yy_chk[1133] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   11,   15,   21,   16,   22,   11,   16,   18,
       18,   15,   16,   35,   16,   25,   49,   26,   28,   57,
       29,   49,   28,   35,   57,   28,  239,   29,  230,   22,
       29,   28,   29,   29,   21,   21,   22,   22,   26,   25,
      154,   29,   55,   35,   35,   25,   25,   26,   26,   27,

       55,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   30,   32,   31,   41,   33,   34,   32,  153,   32,
       37,  151,   33,   34,   32,   32,   36,   30,   33,   34,
       30,   60,   31,  149,  147,   39,  108,  101,   41,   36,
       36,   30,   30,   31,   31,  101,   38,   40,   37,   36,
       37,   37,   36,   38,   39,   62,   36,   36,   38,   38,

       40,   60,   60,   41,   41,   39,   39,   59,   63,  178,
       59,   64,  107,   65,   59,  178,   59,   40,   40,   67,
       68,  106,   66,   69,   70,   62,   62,   68,  102,   67,
       69,   70,  100,   68,   65,   99,   69,   70,   63,   63,
       70,   64,   64,   65,   65,   66,   97,   71,   61,   67,
       67,   72,   66,   66,   71,   73,   73,   58,   72,   53,
       71,   74,   75,   72,   72,   76,   74,   51,   74,   75,
       77,   79,   76,   80,   74,   75,   50,   77,   76,   47,
       75,   76,   78,   77,   81,   82,   73,   73,   77,   78,
       79,  206,   82,   83,   80,   78,   85,  206,   82,   78,

       83,   79,   79,   80,   80,   84,   83,   81,   85,   86,
       83,   46,   84,   87,   81,   81,   88,   84,   84,   85,
       89,   44,   88,  103,   43,   87,   85,   85,   86,   90,
      105,  103,   94,   20,   89,  105,  103,   88,  109,   86,
       86,   92,   87,   87,   87,   91,   88,   88,   93,   90,
       89,   89,   91,   91,  110,   92,   94,   92,   91,   90,
       90,   91,   93,   95,   19,   14,   12,  111,  109,  109,
      114,   92,   92,    7,  112,    6,  114,    5,   93,   93,
      113,   94,   94,   98,  110,  110,  207,   95,  112,   98,
       98,   98,  207,   98,    3,   98,   98,  111,  111,  113,

      114,  114,  115,  148,  112,  112,  115,  116,  148,  115,
      113,  113,   95,   95,  116,  115,  117,  118,  119,  119,
      116,  123,  116,  117,  118,  119,  124,  123,    0,  117,
      118,  119,  117,  117,  120,  121,  122,  126,  120,  125,
      122,  120,  121,  122,  126,  131,  121,  120,  121,  122,
      126,  123,  123,  127,  128,  208,  124,  124,  125,  127,
      127,  208,  129,  131,  132,  137,  127,  130,  128,  125,
      125,    0,  137,  133,  132,  131,  131,  134,  137,  135,
        0,  221,    0,    0,  128,  128,  129,  221,  130,  136,
        0,  134,  129,  129,  132,  132,  133,  130,  130,  136,

      141,  134,  135,  133,  133,  138,  139,  134,  134,  135,
      135,  140,  138,  138,    0,  139,  141,  140,  138,  136,
      136,  155,  222,    0,    0,    0,    0,  158,  222,    0,
      141,  141,    0,    0,  158,  158,  139,  139,  142,  155,
      158,  140,  140,    0,  142,  142,  142,  144,  142,    0,
      142,  155,  155,  144,  144,  144,  145,  144,    0,  144,
        0,  156,  145,  145,  145,  146,  145,    0,  145,  145,
        0,  146,  146,  146,  152,  146,  156,  146,  146,    0,
      152,  152,  152,  157,  152,  162,  152,  152,  159,  165,
      157,  156,  156,  164,    0,  159,  157,  160,  161,  163,

      157,  159,    0,  167,  160,  161,  159,  160,  162,    0,
      160,  161,  165,  161,  164,  162,  162,  166,    0,  165,
      165,  163,  167,  164,  164,  168,    0,  166,  169,  163,
      163,  174,  170,  167,  167,  171,    0,  174,  174,  168,
      170,  172,    0,  171,  174,  175,  169,  166,  166,  190,
      172,  176,    0,    0,    0,  168,  168,  173,  169,  169,
        0,  190,  170,  170,  173,  171,  171,  177,    0,  173,
      173,  172,  172,    0,  176,  175,  175,  177,  179,  190,
      190,  176,  176,    0,  179,  179,  179,    0,  179,    0,
      179,    0,    0,  180,  200,    0,    0,  177,  177,  180,

      180,  180,  182,  180,    0,  180,  200,    0,  182,  182,
      182,  185,  182,    0,  182,  182,    0,  185,  185,  185,
      187,  185,    0,  185,  200,  200,  187,  187,  187,  188,
      187,    0,  187,    0,    0,  188,  188,  188,  189,  188,
      191,  188,  188,  195,  189,  189,  189,  191,  189,  192,
      189,  189,  191,  191,  193,  202,  192,  194,  193,  192,
      196,  193,  192,  197,  194,  198,  195,  193,  202,  194,
      194,  199,  197,  195,  195,  201,  198,  203,  196,  199,
        0,  214,    0,  220,    0,  202,  202,  203,    0,  205,
      196,  196,    0,  197,  197,  198,  198,  204,  201,  220,

        0,  199,  199,  205,  204,  201,  201,  203,  203,  204,
      204,  214,  214,  220,  220,  209,    0,    0,    0,  205,
      205,  209,  209,  209,  210,  209,    0,  209,  217,    0,
      210,  210,  210,  212,  210,  215,  210,  216,  217,  212,
      212,  212,  215,  212,  216,  212,  212,  224,  215,  218,
      216,    0,    0,  215,  216,  226,    0,  219,  217,  217,
      218,  219,  223,    0,  219,  226,  223,    0,  224,  223,
      219,    0,    0,    0,    0,  223,    0,  224,  224,  218,
      218,  225,    0,    0,  225,  226,  226,    0,  225,    0,
        0,    0,    0,    0,  225,  228,    0,  228,  228,  228,

      228,  228,  228,  228,  228,  228,  229,    0,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  231,    0,  231,
        0,    0,    0,    0,  231,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  233,    0,    0,  233,
        0,  233,  233,  234,  234,  234,  235,  235,  236,    0,
        0,    0,    0,    0,    0,  236,  237,    0,    0,    0,
        0,    0,  237,  237,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  240,    0,  240,    0,    0,
        0,    0,  240,  241,  241,  241,  242,    0,    0,  242,
      242,  242,  242,  242,  243,  243,  243,  243,  243,  243,

      243,  243,  243,  243,  243,  244,  244,  245,    0,    0,
        0,    0,    0,    0,  245,  246,    0,    0,    0,    0,
        0,  246,  246,  247,    0,    0,  247,  247,  247,    0,
      247,  248,    0,    0,  248,  248,  248,  248,  248,  249,
        0,    0,  249,  249,  249,  249,  249,  250,    0,    0,
      250,    0,    0,  250,  250,  251,    0,    0,  251,  251,
      251,    0,  251,  252,    0,    0,  252,  252,  252,  252,
      252,  253,    0,    0,  253,    0,    0,  253,  253,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,

      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex_analyzer.lex"
#define INITIAL 0
/* Analisador léxico - Leonardo Veiga, Pedro Accorsi e Rafaela Kreusch*/
/* Todo*/
/* Identificar contexto*/
#line 9 "lex_analyzer.lex"

#define MAX_VAR_LENGTH 30
#define MAX_VARS      100
#define MAX_CONTEXTS   15 

#include <math.h>
#include <stdbool.h>

//struct definition
typedef struct VariableIdentifier{
	char name[30];
	int id;
} varId;

typedef struct ContextIdentifier{
	varId variables[MAX_VARS];
} contextId;

//global var definition
int currentContext    = 0;
int idCounter         = 0 ;
bool isDeclaration    = false;
contextId allContexts[MAX_CONTEXTS];

//global func implementation
void initContexts(){
	for(int i=0; i<MAX_CONTEXTS; i++){
		for(int j=0; j<MAX_VARS; j++){
			allContexts[i].variables[j].name[0] = '\0';
			allContexts[i].variables[j].id      = -1;
		}
	}
}

void enterNewContext(){
	++currentContext;
}

void leaveContext(){
	--currentContext;
}

void addVarToContext(char *varName, int varId){
	for(int i=0; i<MAX_VARS; i++){
		if( allContexts[currentContext].variables[i].id == -1 ){
			allContexts[currentContext].variables[i].id   = varId;
			strcpy(allContexts[currentContext].variables[i].name, varName);
			return;
		}
	}
}

int getId(char *varName){
	int varId = 0;
	if(isDeclaration){
		isDeclaration = false;
		varId = idCounter++;
		addVarToContext(varName, varId);
		return varId;
	}
	for(int i=currentContext; i >= 0; i-- ){ 
		for(int j=0; j<MAX_VARS; j++){
        	if(allContexts[i].variables[j].id == -1)
				break;
				 
			if(strcmp(varName, allContexts[i].variables[j].name) == 0)
				return allContexts[i].variables[j].id;
			
		}
		
	}
	varId = idCounter++;
	addVarToContext(varName, varId);
	return varId;
}

char * cropEndOfLine(char * text){
	int len = strlen(yytext);
	if( yytext[len-1] == '\n')
		yytext[len-1] = 0;
	return yytext;
}

#line 784 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 122 "lex_analyzer.lex"


#line 938 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 228 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1080 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 124 "lex_analyzer.lex"
{ printf("[Line comment: %s]"                       ,cropEndOfLine(yytext))  ;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 125 "lex_analyzer.lex"
{ printf("[comment block]"                          ,cropEndOfLine(yytext))  ;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 126 "lex_analyzer.lex"
{ isDeclaration = true; printf("[reserved_word, %s]", yytext)                ;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 127 "lex_analyzer.lex"
{ printf("[reserved_word, %s]"                      , yytext)                ;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 128 "lex_analyzer.lex"
{ printf("[INCLUDE, %s]"                            , yytext)                ;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 129 "lex_analyzer.lex"
{ printf("[Expressao nao identificada: %s (%d)]"    , yytext, atoi(yytext))  ;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 130 "lex_analyzer.lex"
{ printf("[num, %d]"                                , atoi(yytext))          ;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 131 "lex_analyzer.lex"
{ printf("[num, %s]"                                , yytext)                ;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 132 "lex_analyzer.lex"
{ printf("[%d,  %s]"                                , getId(yytext), yytext) ;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 133 "lex_analyzer.lex"
{ printf("[[string_literal, %s]"                    , yytext)                ;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 134 "lex_analyzer.lex"
{ printf("[Relational_Op, %s]"                      , yytext)                ;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 135 "lex_analyzer.lex"
{ printf("[Arith_Op, %s]"                           , yytext)                ;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 136 "lex_analyzer.lex"
{ printf("[Attrib_Op, %s]"                          , yytext)                ;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 137 "lex_analyzer.lex"
{ printf("[l_paren, %s]"                            , yytext)                ;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 138 "lex_analyzer.lex"
{ printf("[r_paren, %s]"                            , yytext)                ;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 139 "lex_analyzer.lex"
{ enterNewContext(); printf("[l_braces, %s]"        , yytext)                ;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 140 "lex_analyzer.lex"
{ leaveContext();    printf("[r_braces, %s]"        , yytext)                ;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 141 "lex_analyzer.lex"
{ printf("[comma, %s]"                              , yytext)                ;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 142 "lex_analyzer.lex"
{ printf("[semicolon, %s]"                          , yytext)                ;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 143 "lex_analyzer.lex"
{ printf("[l_bracket, %s]"                          , yytext)                ;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 144 "lex_analyzer.lex"
{ printf("[l_bracket, %s]"                          , yytext)                ;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 145 "lex_analyzer.lex"

	YY_BREAK
case 23:
YY_RULE_SETUP
#line 147 "lex_analyzer.lex"
ECHO;
	YY_BREAK
#line 1136 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 228 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 228 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 227);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 147 "lex_analyzer.lex"


int main(int argc, char *argv[]){
	initContexts();
	yyin = fopen(argv[1], "r");
	yylex();
	fclose(yyin);
	return 0;
}
