/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 22
#define YY_END_OF_BUFFER 23
static yyconst short int yy_accept[239] =
    {   0,
        0,    0,   23,   22,   22,   22,   22,   22,   13,   14,
       11,   11,   17,   11,   11,    6,   18,   10,   12,   10,
        8,    8,   19,   20,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,   15,
       16,   10,    0,    9,    0,    8,    0,    0,    8,   11,
        0,    1,    0,    0,    0,    7,    6,    0,    5,    0,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        4,    8,    8,    8,    8,    8,    8,    4,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    0,
       21,    0,    8,    0,    0,    8,    8,    0,    1,    0,

        5,    0,    0,    5,    7,    0,    5,    5,    5,    0,
        0,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    3,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        0,    0,    8,    0,    0,    0,    0,    0,    2,    5,
        0,    0,    5,    5,    0,    0,    0,    0,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        0,    0,    0,    0,    8,    0,    0,    2,    0,    5,
        0,    0,    0,    0,    0,    8,    8,    8,    8,    8,

        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    0,    0,    0,    0,    0,    0,    5,    0,
        0,    5,    3,    8,    8,    8,    8,    8,    8,    0,
        0,    0,    8,    8,    8,    8,    4,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    6,    1,    1,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,    1,   17,   18,
       19,   20,    1,    1,   21,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   21,   23,   22,   22,   22,   22,   22,   21,   22,
       24,    1,   25,   26,    1,    1,   27,   28,   29,   30,

       31,   32,   33,   34,   35,   22,   36,   37,   38,   39,
       40,   41,   22,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   51,    1,   52,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[53] =
    {   0,
        1,    2,    3,    1,    1,    1,    4,    5,    6,    7,
        8,    1,    8,    4,    8,    9,    1,    4,   10,    1,
       11,   11,   11,    1,    1,    1,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       12,   12
    } ;

static yyconst short int yy_base[266] =
    {   0,
        0,    0,  575, 1101,  550,  549,  514,    0, 1101, 1101,
       50,  533, 1101,  527,   52,   49, 1101,  513,  506,  503,
       34,   36, 1101, 1101,   39,   47,   43,   42,   66,   70,
       75,   79,   85,   86,   94,   96,   85,  108,  110,  106,
     1101, 1101,  515,  503,  467,    0,   58,  499,  498, 1101,
      496, 1101,   69,    0,   93,  470,  133,    0,  110,  162,
      112,  188,  195,  190,  191,  202,  200,  210,  116,  216,
      212,  215,  222,  229,  235,  238,  247,  249,  252,  245,
      261,  261,  270,  272,  281,  284,  292,  294,  299,  311,
      315,  444,    0,  465,  340,  454,  453,  320,  436,  342,

        0,  151,  442,  440,  414,  367,  307,  399,  401,  393,
      335,  386,  397,  399,  401,  402,  420,  421,  431,  435,
      440,  445,  443,  454,  455,  457,  465,  469,  477,  401,
      476,  479,  491,  494,  498,  507,  516,  518,  526,  473,
      328,  552, 1101,  561,  570,  579,  354,  211,  359,    0,
      357,  588,  320,  304,  268,  256,  236,   58,  520,  569,
      563,  575,  576,  579,  583,  589,  593,  601,  607,  608,
      608,  623,  622,  623,  635,  636,  628,  648,  649,  661,
      196,   72,  692,  701, 1101,  710,    0, 1101,  719, 1101,
      728,  737,  746,  218,  251,  189,  721,  641,  669,  696,

      726,  727,  731,  743,  744,  748,  751,  756,  767,  771,
      769,  775,  190,  236,  336,  337,  815,  824, 1101,  833,
        0,  185,  783,  808,  813,  823,  826,  833,  829,  129,
      345,  484,  836,  841,  849,  854, 1101, 1101,  902,  145,
      912,  923,  932,  934,  937,  941,  950,  959,  970,   63,
      980,   61,  983,  993, 1004, 1008, 1017, 1026, 1035, 1044,
     1053, 1062, 1071, 1080, 1089
    } ;

static yyconst short int yy_def[266] =
    {   0,
      238,    1,  238,  238,  238,  239,  238,  240,  238,  238,
      241,  238,  238,  238,  242,  243,  238,  244,  238,  238,
      245,  245,  238,  238,  245,  245,  245,   27,   27,   27,
       27,   29,   27,   27,   27,   27,   29,   27,   27,  238,
      238,  238,  239,  239,  238,  246,  241,  247,  248,  238,
      242,  238,  249,  250,  251,  238,  243,  252,  253,  238,
       27,   27,  238,   27,   27,   27,   27,   27,   29,   29,
       29,   29,   29,   29,   27,   27,   27,   27,   27,   29,
       29,   27,   27,   27,   27,   27,   27,   29,   29,  238,
      238,  238,  246,  247,  254,  238,  248,  249,  255,  249,

      256,  251,  257,  258,  238,  238,  253,  253,  238,  238,
       60,   29,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   29,
       29,   29,   29,   29,   29,   27,   27,   27,   27,   29,
      238,  259,  238,  259,  254,  260,  255,  255,  242,  256,
      257,  261,  238,  258,  238,  106,  238,   60,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       27,   27,   29,   29,   29,   29,   29,   29,   29,   29,
      238,  262,  259,  259,  238,  260,  186,  238,  263,  238,
      263,  261,  264,  238,  106,  238,   29,   29,   29,   29,

       29,   29,   29,   29,   29,   29,   29,   29,   27,   27,
       29,   29,  238,  238,  262,  265,  263,  263,  238,  264,
      220,  238,   29,   29,   29,   29,   29,   29,   29,  238,
      238,  265,   29,   29,   29,   29,  238,    0,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238
    } ;

static yyconst short int yy_nxt[1154] =
    {   0,
        4,    4,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,    4,   15,   16,   17,   18,   19,   20,
       21,   21,   22,   23,   24,    4,   25,   26,   27,   28,
       29,   30,   31,   21,   32,   21,   33,   21,   21,   21,
       21,   34,   35,   36,   37,   38,   39,   21,   21,   21,
       40,   41,   47,   52,   62,   54,   62,   48,   55,   62,
       47,   53,   56,   62,   57,   48,   58,   62,   61,   67,
       99,  106,   70,  101,  214,   61,   68,  196,  100,   64,
      143,   71,   69,   65,   63,   63,   63,   63,   66,   63,
       63,  158,   61,   63,   63,  102,   61,   63,   63,   61,

      103,   61,   72,   61,   73,   61,   75,   90,   61,   76,
       78,   61,   61,   74,   77,   61,   81,   79,   61,   61,
       61,   61,   61,   87,   80,   61,   61,   82,   83,   61,
      108,   90,   61,   61,   61,   61,   61,   84,   61,   54,
       85,   61,   55,   89,   86,   61,  238,   88,   57,   61,
       58,   61,   61,  102,  117,   46,   90,   91,  103,  237,
      109,  109,  110,   61,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  111,  110,  110,
      110,  110,  111,  111,  111,  110,  110,  110,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,

      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  110,  110,   61,   63,   61,   61,  194,  230,
      148,   61,  157,   61,   61,  188,   61,   61,   61,   61,
       61,  112,  114,   61,  113,   61,  116,  190,  214,   61,
      213,   61,  115,   61,  143,   63,   63,  118,   61,   61,
       61,   61,   61,   61,   61,  143,  119,  120,   61,   61,
       61,   61,   61,   61,   61,   61,  121,   61,   61,   61,
      222,   61,  122,   61,  123,   61,   61,   61,   61,   78,
       61,   61,   61,  126,  195,   61,   61,   61,   61,  195,
      124,   61,   61,  127,   61,  125,   61,   61,  132,   61,

      129,  194,  130,   61,  128,   61,  153,   61,   61,   61,
       61,   61,   90,  133,   61,  134,   90,   61,   61,  131,
       61,   99,  153,   61,  135,   61,  136,  108,  138,  100,
      139,   61,   61,  140,  137,   61,   90,   61,  214,  231,
       90,   61,  142,   99,  143,  190,   61,  231,  143,  144,
      144,  100,  144,  190,  144,  145,  149,  109,  109,  151,
       52,   90,   91,  148,  181,   90,   91,  155,  158,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  156,  155,  155,  155,  155,  156,  156,  156,
      155,  155,  155,  156,  156,  156,  156,  156,  156,  156,

      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  155,  155,  108,
      159,  109,   61,   61,   61,  160,  157,   61,   61,  105,
       61,   78,   61,   61,   61,   61,   78,   61,   61,  170,
       61,   61,  153,  125,  151,  148,   61,  163,   61,  109,
      109,  109,  109,   61,   61,   96,   96,   61,  164,   61,
       61,   61,  161,  162,   61,   78,   61,   94,   61,  166,
       61,   61,  141,   61,   61,  165,   61,   78,   61,   61,
       61,   61,   61,   61,   61,  105,  231,   61,   61,   78,
       61,   61,  190,   78,   61,   61,   61,   52,   61,  167,

       96,   94,   61,   61,   61,   92,  171,   44,   61,  180,
       61,   61,   61,  168,   61,   61,   61,   61,  169,   44,
       61,   42,  172,   61,   42,  173,   61,   61,  176,   61,
       61,   42,   61,   61,   61,  174,   61,  175,   61,   50,
       61,   61,   61,   50,   61,   61,  177,  125,   45,   61,
      178,   61,  179,   44,  142,   61,   61,   61,  197,   61,
      143,  144,  144,  183,  144,   61,  144,   61,   42,  238,
      144,  144,  142,  144,  238,  144,  238,  238,  143,  144,
      144,  184,  144,  238,  144,  145,  238,  185,  144,  144,
      189,  144,  238,  144,  186,  238,  190,  191,  191,   61,

      191,   61,  191,  192,   78,   61,   78,   61,  238,  198,
       61,   61,   61,   61,   61,  200,   61,   61,  238,   61,
      199,   61,   61,   61,  201,   61,   61,   61,  238,   61,
       61,   61,  125,  238,   61,  202,   61,   61,  204,   61,
       61,   61,  203,   61,   61,   61,   61,  205,   61,   61,
       78,  208,  238,  238,   61,   61,   61,  206,   61,   61,
      207,   61,   61,  209,   61,  210,   78,  238,  238,   61,
       61,   61,   61,   61,   61,   61,  238,   61,  238,  224,
      211,  238,   61,   61,   61,   61,   61,   61,   61,  238,
      238,   78,  212,  238,  183,   61,   61,   61,  238,   61,

      238,  238,  238,  184,  238,  225,  238,   61,   61,  185,
      144,  144,  184,  144,  238,  144,   61,  238,  185,  144,
      144,  189,  144,  238,  144,  186,  125,  190,  191,  191,
      217,  191,   61,  191,   61,  238,  238,  191,  191,  189,
      191,  238,  191,   61,  238,  190,  191,  191,  218,  191,
      238,  191,  192,  223,  219,  191,  191,   61,  191,   61,
      191,  220,   61,   61,   78,   61,  238,   61,   61,   78,
      226,  238,   78,   61,   61,   78,   78,  238,   61,   61,
       61,   61,   61,  125,   61,  238,   61,   61,  238,   61,
       61,   61,   61,   61,   61,   61,  238,   61,   61,   78,

       78,  227,  238,   61,   61,   61,   61,  228,  238,  229,
       61,   61,  238,   61,  238,  238,   61,  217,  238,   61,
      238,   61,   61,  238,  238,  238,  218,  238,  238,  238,
       61,  238,  219,  191,  191,  218,  191,  238,  191,  238,
      238,  219,  191,  191,   61,  191,   61,  191,  220,   61,
      238,   61,  233,  234,  238,   61,   78,   78,  238,   61,
       61,   61,   61,  235,   61,  236,   78,   61,  238,   61,
       61,   61,   61,   61,   61,  238,   61,   61,   78,   61,
       61,  238,   78,   61,   78,   61,  238,   61,   61,  238,
       61,  238,   61,  238,  238,  238,   61,  238,  238,  238,

      238,   61,   43,  238,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   49,  238,   49,  238,  238,  238,
      238,  238,   49,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   59,  238,  238,   59,  238,
       59,  238,   59,   60,   60,   61,  238,   61,   61,   93,
      238,   93,   95,  238,  238,  238,  238,  238,  238,  238,
       95,   97,  238,  238,  238,  238,  238,   97,  238,   97,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,  104,  238,  104,  238,  238,  238,  238,  238,
      104,  107,  238,  107,  107,  146,  238,  238,  146,  146,

      146,  146,  238,  146,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  150,  238,  150,  152,
      238,  238,  238,  238,  238,  238,  238,  152,  154,  238,
      238,  238,  238,  238,  154,  238,  154,  182,  238,  238,
      182,  182,  182,  238,  238,  182,  187,  238,  238,  187,
      187,  187,  187,  238,  187,  193,  238,  238,  193,  193,
      193,  193,  238,  193,  215,  238,  238,  215,  238,  238,
      215,  238,  215,  216,  238,  238,  216,  216,  216,  238,
      238,  216,  221,  238,  238,  221,  221,  221,  221,  238,
      221,  232,  238,  238,  232,  238,  238,  232,  238,  232,

        3,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238
    } ;

static yyconst short int yy_chk[1154] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   11,   15,   21,   16,   22,   11,   16,   25,
       47,   15,   16,   27,   16,   47,   16,   26,   28,   27,
       53,  252,   28,  250,  182,   28,   27,  158,   53,   22,
      182,   28,   27,   25,   21,   21,   22,   22,   26,   25,
       25,  158,   29,   27,   27,   55,   30,   26,   26,   29,

       55,   31,   29,   30,   29,   29,   30,   40,   31,   30,
       32,   33,   34,   29,   31,   32,   34,   32,   33,   34,
       35,   37,   36,   37,   33,   34,   32,   35,   35,   36,
       59,   40,   37,   35,   38,   36,   39,   35,   61,   57,
       35,   38,   57,   39,   36,   61,   57,   38,   57,   39,
       57,   61,   69,  102,   69,  240,   40,   40,  102,  230,
       59,   59,   60,   69,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,

       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   62,   63,   64,   65,  222,  213,
      148,   62,  196,   64,   65,  148,   67,   62,   66,   64,
       65,   64,   66,   67,   65,   66,   68,  194,  214,   67,
      181,   66,   67,   68,  214,   63,   63,   70,   71,   68,
       71,   72,   70,   72,   70,  157,   71,   72,   73,   71,
       73,   75,   72,   70,   76,   74,   73,   74,   75,   73,
      195,   76,   74,   77,   75,   78,   74,   76,   79,   76,
       77,   80,   78,   80,  195,   79,   77,   82,   78,  156,
       77,   79,   80,   81,   82,   79,   83,   81,   84,   81,

       82,  155,   83,   83,   81,   84,  154,   85,   81,   83,
       86,   84,   90,   84,   85,   85,   91,   86,   87,   83,
       85,   98,  153,   86,   86,   87,   87,  107,   88,   98,
       88,   87,   88,   89,   87,   89,   90,   89,  215,  216,
       91,   88,   95,  100,  215,  216,   89,  231,   95,   95,
       95,  100,   95,  231,   95,   95,  100,  107,  107,  151,
      149,   90,   90,  147,  141,   91,   91,  106,  111,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,

      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  108,
      112,  109,  112,  113,  112,  114,  110,  115,  116,  105,
      113,  115,  114,  112,  115,  116,  113,  130,  114,  130,
      115,  116,  104,  116,  103,   99,  117,  118,  130,  108,
      108,  109,  109,  117,  118,   97,   96,  119,  119,  117,
      118,  120,  117,  117,  119,  120,  121,   94,  120,  123,
      119,  122,   92,  121,  120,  122,  123,  121,  122,  121,
      124,  125,  123,  126,  122,   56,  232,  124,  125,  126,
      126,  127,  232,  124,  125,  128,  126,   51,  127,  127,

       49,   48,  128,  129,  127,   45,  131,   44,  128,  140,
      129,  140,  131,  128,  131,  132,  129,  132,  129,   43,
      140,   20,  132,  131,   19,  133,  132,  133,  135,  133,
      134,   18,  134,  136,  135,  133,  135,  134,  133,   14,
      136,  134,  137,   12,  138,  135,  136,  138,    7,  137,
      137,  138,  139,    6,  142,  137,  159,  138,  159,  139,
      142,  142,  142,  144,  142,  139,  142,  159,    5,  144,
      144,  144,  145,  144,    3,  144,    0,    0,  145,  145,
      145,  146,  145,    0,  145,  145,    0,  146,  146,  146,
      152,  146,    0,  146,  146,    0,  152,  152,  152,  161,

      152,  161,  152,  152,  160,  160,  161,  160,    0,  162,
      161,  162,  163,  162,  163,  164,  160,  164,    0,  165,
      163,  165,  162,  163,  165,  166,  164,  166,    0,  167,
      165,  167,  166,    0,  171,  167,  166,  168,  170,  168,
      167,  171,  168,  169,  170,  169,  170,  171,  168,  172,
      169,  174,    0,    0,  169,  170,  172,  172,  173,  174,
      173,  174,  172,  175,  177,  176,  177,    0,    0,  173,
      174,  175,  176,  175,  176,  177,    0,  198,    0,  198,
      178,    0,  175,  176,  178,  179,  178,  179,  198,    0,
        0,  180,  179,    0,  183,  178,  179,  180,    0,  180,

      183,  183,  183,  184,  183,  199,  183,  199,  180,  184,
      184,  184,  186,  184,    0,  184,  199,    0,  186,  186,
      186,  189,  186,    0,  186,  186,  200,  189,  189,  189,
      191,  189,  200,  189,  200,    0,  191,  191,  191,  192,
      191,    0,  191,  200,    0,  192,  192,  192,  193,  192,
        0,  192,  192,  197,  193,  193,  193,  197,  193,  197,
      193,  193,  201,  202,  201,  202,    0,  203,  197,  203,
      202,    0,  204,  201,  202,  205,  206,    0,  203,  204,
      205,  204,  205,  207,  206,    0,  206,  207,    0,  207,
      204,  205,  208,  209,  208,  206,    0,  210,  207,  208,

      209,  210,    0,  208,  210,  211,  209,  211,    0,  212,
      210,  212,    0,  212,    0,    0,  211,  217,    0,  223,
        0,  223,  212,  217,  217,  217,  218,  217,    0,  217,
      223,    0,  218,  218,  218,  220,  218,    0,  218,    0,
        0,  220,  220,  220,  224,  220,  224,  220,  220,  225,
        0,  225,  224,  226,    0,  224,  225,  227,    0,  226,
      225,  226,  227,  228,  227,  229,  233,  229,    0,  228,
      226,  228,  233,  227,  233,    0,  229,  234,  235,  234,
      228,    0,  234,  233,  236,  235,    0,  235,  234,    0,
      236,    0,  236,    0,    0,    0,  235,    0,    0,    0,

        0,  236,  239,    0,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  241,    0,  241,    0,    0,    0,
        0,    0,  241,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  243,    0,    0,  243,    0,
      243,    0,  243,  244,  244,  245,    0,  245,  245,  246,
        0,  246,  247,    0,    0,    0,    0,    0,    0,    0,
      247,  248,    0,    0,    0,    0,    0,  248,    0,  248,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  251,    0,  251,    0,    0,    0,    0,    0,
      251,  253,    0,  253,  253,  254,    0,    0,  254,  254,

      254,  254,    0,  254,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  256,    0,  256,  257,
        0,    0,    0,    0,    0,    0,    0,  257,  258,    0,
        0,    0,    0,    0,  258,    0,  258,  259,    0,    0,
      259,  259,  259,    0,    0,  259,  260,    0,    0,  260,
      260,  260,  260,    0,  260,  261,    0,    0,  261,  261,
      261,  261,    0,  261,  262,    0,    0,  262,    0,    0,
      262,    0,  262,  263,    0,    0,  263,  263,  263,    0,
        0,  263,  264,    0,    0,  264,  264,  264,  264,    0,
      264,  265,    0,    0,  265,    0,    0,  265,    0,  265,

      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex_analyzer.lex"
#define INITIAL 0
/* Analisador léxico - Leonardo Veiga, Pedro Accorsi e Rafaela Kreusch*/
/* Todo*/
/* Identificar contexto*/
#line 9 "lex_analyzer.lex"

#define MAX_VAR_LENGTH 30
#define MAX_VARS       100
#define MAX_CONTEXTS   15 

#include <math.h>
#include <stdbool.h>

//struct definition
typedef struct VariableIdentifier{
	char name[30];
	int id;
} varId;

typedef struct ContextIdentifier{
	varId variables[MAX_VARS];
} contextId;

enum ErrorIdentifier{
	var_overflow,
	var_length_overflow,
	context_overflow,
	context_underflow
} errorId;

//global var definition
int currentContext    = 0;
int idCounter         = 0 ;
bool isDeclaration    = false;
contextId allContexts[MAX_CONTEXTS];

//global func implementation
void initContexts(){
	for(int i=0; i<MAX_CONTEXTS; i++){
		for(int j=0; j<MAX_VARS; j++){
			allContexts[i].variables[j].name[0] = '\0';
			allContexts[i].variables[j].id      = -1;
		}
	}
}

void enterNewContext(){
	++currentContext;
	if(currentContext > MAX_CONTEXTS)
		FATAL_ERROR(context_overflow);
}

void leaveContext(){
	--currentContext;
	if(currentContext < 0)
		FATAL_ERROR(context_underflow);
}

void addVarToContext(char *varName, int varId){
	if(strlen(varName) > MAX_VAR_LENGTH)
		FATAL_ERROR(var_length_overflow);

	for(int i=0; i<MAX_VARS; i++){
		if( allContexts[currentContext].variables[i].id == -1 ){
			allContexts[currentContext].variables[i].id   = varId;
			strcpy(allContexts[currentContext].variables[i].name, varName);
			return;
		}
	}
	YY_FATAL_ERROR("123");
}

void FATAL_ERROR( int error ){
	char errorMsg[500];
	switch(error){
		case var_overflow:        sprintf(errorMsg, "fatal variable error -- max number of variables (%d) per context reached", MAX_VARS)    ; break;
		case var_length_overflow: sprintf(errorMsg, "fatal variable error -- variable length greater than max allowed (%d) ", MAX_VAR_LENGTH); break;
		case context_overflow:    sprintf(errorMsg, "fatal context error -- max number of contexts (%d) reached", MAX_CONTEXTS)              ; break;
		case context_underflow:   sprintf(errorMsg, "fatal context error -- illegal attempt to leave unopened context")                      ; break;
	}
	(void) fprintf( stderr, "%s\n", errorMsg );
	exit( -1 );
}

int getId(char *varName){
	int varId = 0;
	if(isDeclaration){
		isDeclaration = false;
		varId = idCounter++;
		addVarToContext(varName, varId);
		return varId;
	}
	for(int i=currentContext; i >= 0; i-- ){ 
		for(int j=0; j<MAX_VARS; j++){
        	if(allContexts[i].variables[j].id == -1)
				break;
				 
			if(strcmp(varName, allContexts[i].variables[j].name) == 0)
				return allContexts[i].variables[j].id;
			
		}
		
	}
	varId = idCounter++;
	addVarToContext(varName, varId);
	return varId;
}

char * cropEndOfLine(char * text){
	int len = strlen(yytext);
	if( yytext[len-1] == '\n')
		yytext[len-1] = 0;
	return yytext;
}

#line 818 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 149 "lex_analyzer.lex"


#line 972 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 239 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1101 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 151 "lex_analyzer.lex"
{ printf("[Line comment: %s]"                       ,cropEndOfLine(yytext))  ;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 152 "lex_analyzer.lex"
{ printf("[comment block]"                          ,cropEndOfLine(yytext))  ;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 153 "lex_analyzer.lex"
{ isDeclaration = true; printf("[reserved_word, %s]", yytext)                ;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 154 "lex_analyzer.lex"
{ printf("[reserved_word, %s]"                      , yytext)                ;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 155 "lex_analyzer.lex"
{ printf("[Expressao nao identificada: %s (%d)]"    , yytext, atoi(yytext))  ;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 156 "lex_analyzer.lex"
{ printf("[num, %d]"                                , atoi(yytext))          ;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 157 "lex_analyzer.lex"
{ printf("[num, %s]"                                , yytext)                ;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 158 "lex_analyzer.lex"
{ printf("[%d,  %s]"                                , getId(yytext), yytext) ;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 159 "lex_analyzer.lex"
{ printf("[[string_literal, %s]"                    , yytext)                ;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 160 "lex_analyzer.lex"
{ printf("[Relational_Op, %s]"                      , yytext)                ;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 161 "lex_analyzer.lex"
{ printf("[Arith_Op, %s]"                           , yytext)                ;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 162 "lex_analyzer.lex"
{ printf("[Attrib_Op, %s]"                          , yytext)                ;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 163 "lex_analyzer.lex"
{ printf("[l_paren, %s]"                            , yytext)                ;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 164 "lex_analyzer.lex"
{ printf("[r_paren, %s]"                            , yytext)                ;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 165 "lex_analyzer.lex"
{ enterNewContext(); printf("[l_braces, %s]"        , yytext)                ;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 166 "lex_analyzer.lex"
{ leaveContext();    printf("[r_braces, %s]"        , yytext)                ;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 167 "lex_analyzer.lex"
{ printf("[comma, %s]"                              , yytext)                ;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 168 "lex_analyzer.lex"
{ printf("[semicolon, %s]"                          , yytext)                ;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 169 "lex_analyzer.lex"
{ printf("[l_bracket, %s]"                          , yytext)                ;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 170 "lex_analyzer.lex"
{ printf("[l_bracket, %s]"                          , yytext)                ;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 171 "lex_analyzer.lex"

	YY_BREAK
case 22:
YY_RULE_SETUP
#line 173 "lex_analyzer.lex"
ECHO;
	YY_BREAK
#line 1165 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 239 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 239 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 238);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 173 "lex_analyzer.lex"


int main(int argc, char *argv[]){
	initContexts();
	yyin = fopen(argv[1], "r");
	yylex();
	fclose(yyin);
	return 0;
}
