/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 24
#define YY_END_OF_BUFFER 25
static yyconst short int yy_accept[190] =
    {   0,
        0,    0,   25,   24,   24,   24,   24,   21,   13,   14,
       11,   11,   17,   11,   11,    6,   18,   10,   12,   10,
        8,    8,    8,   19,   20,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
       15,   16,   10,    0,    9,    0,   11,    0,    1,    0,
        7,    6,    5,    0,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    4,    8,    8,    8,    8,
        8,    8,    4,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    0,   23,    0,    0,    1,    0,
        7,    5,    5,    5,    0,    0,    8,    8,    8,    8,

        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        3,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    0,    0,    0,    2,
        0,    0,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    0,    2,   22,   22,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    0,    3,    8,    8,    8,    8,
        8,    8,    0,    8,    8,    8,    8,    4,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    1,    1,    6,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,    1,   16,   17,
       18,   19,    1,    1,   20,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   22,   21,   23,   21,   21,
       21,   20,   24,   21,   25,   21,   21,   21,   20,   21,
       26,    1,   27,   28,    1,    1,   29,   30,   31,   32,

       33,   34,   35,   36,   37,   21,   38,   39,   40,   41,
       42,   43,   21,   44,   45,   46,   47,   48,   49,   50,
       51,   52,   53,    1,   54,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[55] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    1,    4,    1,    1,    5,    1,    6,
        6,    6,    6,    6,    6,    1,    1,    1,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    7,    7
    } ;

static yyconst short int yy_base[198] =
    {   0,
        0,    0,  182,  844,  163,  176,  140,  844,  844,  844,
      844,  165,  844,  162,   53,   43,  844,  155,  154,  153,
       37,   39,   41,  844,  844,   49,   45,   68,   81,   66,
       86,   58,   95,   88,   93,  107,  104,   97,  112,  132,
      135,  844,  844,  166,  165,  126,  844,  162,  844,   58,
      147,   53,  125,  189,  224,  226,  228,  230,  241,  243,
      233,  245,  238,  252,  254,  256,  280,  282,  284,  297,
      299,  294,  291,  303,  301,  326,  321,  338,  340,  344,
      342,  362,  350,  368,  273,  374,  102,   61,  122,   70,
      103,  312,  347,  357,   73,   49,  386,  389,  392,  394,

      397,  400,  411,  409,  405,  416,  421,  435,  447,  440,
      432,  452,  458,  460,  464,  478,  470,  476,  489,  495,
      500,  505,  484,  507,  515,  525,   44,   73,   62,   79,
       61,  140,  530,  532,  520,  535,  543,  555,  547,  557,
      560,  562,  572,  579,  575,  567,  582,  599,  607,  602,
      604,  611,  617,  621,   30,  844,  844,   39,  624,  627,
      630,  646,  652,  642,  656,  662,  667,  671,  669,  665,
      678,  693,  687,  697,   42,  683,  707,  709,  715,  718,
      723,  725,   40,  733,  729,  738,  747,  844,  844,  801,
      808,  813,  815,  818,  825,  829,  836

    } ;

static yyconst short int yy_def[198] =
    {   0,
      189,    1,  189,  189,  189,  190,  189,  189,  189,  189,
      189,  189,  189,  189,  191,  192,  189,  193,  189,  189,
      194,  194,  194,  189,  189,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      189,  189,  189,  190,  190,  189,  189,  191,  189,  195,
      189,  192,  196,  189,  194,  194,  189,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  189,  189,  189,  195,  197,  195,
      189,  196,  196,  189,  189,   54,  194,  194,  194,  194,

      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  189,  197,  197,  191,
      189,   54,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  189,  189,  189,  189,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  189,  194,  194,  194,  194,  194,
      194,  194,  189,  194,  194,  194,  194,  189,    0,  189,
      189,  189,  189,  189,  189,  189,  189

    } ;

static yyconst short int yy_nxt[899] =
    {   0,
        4,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,    4,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   22,   23,   21,   24,   25,    4,   26,   27,
       28,   29,   30,   31,   32,   21,   33,   21,   34,   21,
       21,   21,   21,   35,   36,   37,   38,   39,   40,   21,
       21,   21,   41,   42,   49,   51,   56,   52,   56,   89,
       56,   50,   89,   58,   56,  189,   90,   52,   56,   90,
      129,   89,  188,  183,  131,  156,  175,   56,   90,  157,
       49,  129,  155,  130,  132,   56,   59,   56,   61,   57,
       57,   57,   57,   57,   57,   60,   62,   57,   57,   72,

       56,   57,   57,   63,   67,   56,   68,   56,  131,   64,
       57,   57,   56,   65,   56,   69,   56,   91,   57,   57,
       57,   57,   66,   56,   70,   76,   56,   71,   73,   75,
      129,   56,  127,   57,   57,   74,   85,   82,   57,   57,
       57,   57,   77,   78,   93,   57,   57,   57,   57,   57,
       57,   56,   79,   83,   81,   80,   57,   57,  158,   57,
       57,   91,   85,   49,   57,   57,   87,   84,   45,   45,
       43,   43,   43,   47,   47,  132,   46,   94,   94,   45,
       43,  189,  189,  189,   57,   57,  189,   85,   86,   95,
      189,   95,   95,   95,   95,   95,   95,   95,   95,   95,

       95,   95,   95,   96,   95,   95,   95,   95,   96,   96,
       96,   96,   96,   96,   95,   95,   95,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   95,   95,   56,  189,   56,  189,   57,  189,   56,
      189,   97,   56,  189,  189,  189,  189,   56,  189,  189,
       56,  189,   56,  189,   56,  100,  102,  189,  189,  189,
      189,   56,  189,   56,   85,   56,   57,   57,   57,   57,
       57,   57,   57,   57,   98,   57,   57,  104,   99,  101,
       57,   57,  103,   57,   57,   57,   57,   57,   57,   56,

       85,   56,  105,   56,   57,   57,   57,   57,   57,   57,
       56,  189,  189,   56,  189,  189,   56,  189,   56,  189,
       56,  189,   56,  189,  106,   85,   86,  189,  107,  108,
      189,   93,   57,   57,   57,   57,   57,   57,  109,  110,
       56,  112,   73,   57,   57,   56,   57,   57,  111,   57,
       57,   57,   57,   57,   57,   57,   57,   56,  189,   56,
      113,   56,  115,   56,   94,   94,   93,  189,  118,   56,
      189,  114,  116,   57,   57,   85,   94,  189,   57,   57,
      120,   56,  189,  119,  121,  189,  124,   56,  125,  117,
       57,   57,   57,   57,   57,   57,   57,   57,  122,   94,

       94,   85,   57,   57,  126,   56,  123,   73,   56,   94,
       94,   56,  189,   56,   57,   57,   56,  189,  189,   56,
       57,   57,  134,  189,   56,  133,   85,   86,   56,   73,
       56,  189,  189,   73,  138,   56,  189,  137,   57,   57,
       56,   57,   57,  111,   57,   57,   57,   57,   73,   57,
       57,   56,   57,   57,   56,  135,  136,   57,   57,   56,
       73,   57,   57,   57,   57,  189,   56,  139,   57,   57,
      189,   56,  189,   57,   57,  140,  189,   56,  189,   56,
      189,   73,  189,   56,   57,   57,   73,   57,   57,   56,
      189,  189,   57,   57,  141,   56,  189,   56,  189,   57,

       57,  189,  145,   56,   57,   57,  142,  143,   56,  189,
       57,   57,   57,   57,   56,  189,   57,   57,  144,   56,
      152,  146,   57,   57,   56,  147,   56,  189,   57,   57,
       57,   57,  150,  189,   56,  148,   57,   57,  111,   56,
      149,   57,   57,  153,   56,  189,  151,   57,   57,   56,
      189,   56,   57,   57,   56,  189,  189,   57,   57,   57,
       57,  189,   56,  154,  189,   73,   56,   57,   57,   73,
      159,  160,   57,   57,   56,  189,   56,   57,   57,   56,
      189,   56,   57,   57,   57,   57,   56,   57,   57,  161,
      163,   56,  189,  162,   56,   57,   57,  189,   56,   57,

       57,   56,  111,  168,  164,  165,  189,   57,   57,   57,
       57,  166,   57,   57,   57,   57,  167,   73,   56,   57,
       57,   56,  169,   56,   57,   57,   56,   57,   57,  170,
       56,   57,   57,  172,   57,   57,   56,  171,  189,  189,
       56,  189,  189,   56,   73,  173,   56,  189,  189,   56,
      189,   57,   57,   73,   57,   57,   57,   57,  176,   57,
       57,   56,  174,   57,   57,   56,  189,  177,  178,   57,
       57,   56,  189,   57,   57,   56,   57,   57,  111,   57,
       57,   56,   57,   57,   56,  189,   56,  179,   56,  189,
       56,  189,   73,   73,   57,   57,   73,   56,   57,   57,

       73,   73,   56,  111,   57,   57,   56,  189,   57,   57,
       73,  189,   56,   73,   57,   57,   56,   57,   57,   57,
       57,   57,   57,   57,   57,  180,   56,  181,   56,  189,
       57,   57,  189,  182,   56,   57,   57,   56,  189,   57,
       57,  189,   56,  189,   56,   57,   57,  185,   56,   57,
       57,   73,   56,  184,   73,  186,  189,   56,  189,   57,
       57,   57,   57,  187,  189,   73,   56,   57,   57,   73,
       57,   57,   73,  189,  189,   57,   57,   57,   57,   73,
      189,   57,   57,  189,  189,   57,   57,  189,  189,  189,
       57,   57,  189,  189,  189,  189,  189,  189,  189,   57,

       57,   44,  189,   44,   44,   44,   44,   44,   48,   48,
       48,   48,   48,   48,   48,   53,   53,  189,   53,   54,
       54,   55,  189,   55,   55,   88,   88,   88,   88,   88,
       88,   88,   92,  189,   92,   92,  128,  128,  128,  128,
      128,  128,  128,    3,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189

    } ;

static yyconst short int yy_chk[899] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   15,   16,   21,   16,   22,   50,
       23,   15,   88,   22,   27,   52,   50,   52,   26,   88,
      129,   90,  183,  175,  158,  129,  155,   32,   90,  131,
      130,  128,  127,   90,   96,   30,   23,   28,   27,   21,
       21,   22,   22,   23,   23,   26,   28,   27,   27,   32,

       29,   26,   26,   28,   30,   31,   30,   34,   95,   28,
       32,   32,   35,   29,   33,   30,   38,   91,   30,   30,
       28,   28,   29,   37,   31,   35,   36,   31,   33,   34,
       89,   39,   87,   29,   29,   33,   41,   38,   31,   31,
       34,   34,   36,   36,   53,   35,   35,   33,   33,   38,
       38,   40,   36,   39,   37,   36,   37,   37,  132,   36,
       36,   51,   41,   48,   39,   39,   46,   40,   45,   44,
       20,   19,   18,   14,   12,  132,    7,   53,   53,    6,
        5,    3,    0,    0,   40,   40,    0,   41,   41,   54,
        0,   54,   54,   54,   54,   54,   54,   54,   54,   54,

       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   55,    0,   56,    0,   57,    0,   58,
        0,   58,   61,    0,    0,    0,    0,   63,    0,    0,
       59,    0,   60,    0,   62,   61,   63,    0,    0,    0,
        0,   64,    0,   65,   85,   66,   55,   55,   56,   56,
       57,   57,   58,   58,   59,   61,   61,   65,   60,   62,
       63,   63,   64,   59,   59,   60,   60,   62,   62,   67,

       85,   68,   66,   69,   64,   64,   65,   65,   66,   66,
       73,    0,    0,   72,    0,    0,   70,    0,   71,    0,
       75,    0,   74,    0,   67,   85,   85,    0,   68,   69,
        0,   92,   67,   67,   68,   68,   69,   69,   70,   72,
       77,   75,   71,   73,   73,   76,   72,   72,   74,   70,
       70,   71,   71,   75,   75,   74,   74,   78,    0,   79,
       76,   81,   77,   80,   92,   92,   93,    0,   79,   83,
        0,   76,   78,   77,   77,   86,   94,    0,   76,   76,
       80,   82,    0,   79,   81,    0,   83,   84,   83,   78,
       78,   78,   79,   79,   81,   81,   80,   80,   82,   93,

       93,   86,   83,   83,   84,   97,   82,   97,   98,   94,
       94,   99,    0,  100,   82,   82,  101,    0,    0,  102,
       84,   84,  100,    0,  105,   98,   86,   86,  104,  101,
      103,    0,    0,   99,  105,  106,    0,  104,   97,   97,
      107,   98,   98,  102,   99,   99,  100,  100,  106,  101,
      101,  111,  102,  102,  108,  103,  103,  105,  105,  110,
      107,  104,  104,  103,  103,    0,  109,  108,  106,  106,
        0,  112,    0,  107,  107,  109,    0,  113,    0,  114,
        0,  110,    0,  115,  111,  111,  112,  108,  108,  117,
        0,    0,  110,  110,  113,  118,    0,  116,    0,  109,

      109,    0,  117,  123,  112,  112,  114,  115,  119,    0,
      113,  113,  114,  114,  120,    0,  115,  115,  116,  121,
      123,  118,  117,  117,  122,  119,  124,    0,  118,  118,
      116,  116,  121,    0,  125,  119,  123,  123,  124,  135,
      120,  119,  119,  125,  126,    0,  122,  120,  120,  133,
        0,  134,  121,  121,  136,    0,    0,  122,  122,  124,
      124,    0,  137,  126,    0,  135,  139,  125,  125,  134,
      133,  136,  135,  135,  138,    0,  140,  126,  126,  141,
        0,  142,  133,  133,  134,  134,  146,  136,  136,  137,
      139,  143,    0,  138,  145,  137,  137,    0,  144,  139,

      139,  147,  140,  146,  141,  142,    0,  138,  138,  140,
      140,  144,  141,  141,  142,  142,  145,  143,  148,  146,
      146,  150,  147,  151,  143,  143,  149,  145,  145,  148,
      152,  144,  144,  150,  147,  147,  153,  149,    0,    0,
      154,    0,    0,  159,  151,  152,  160,    0,    0,  161,
        0,  148,  148,  154,  150,  150,  151,  151,  159,  149,
      149,  164,  153,  152,  152,  162,    0,  160,  161,  153,
      153,  163,    0,  154,  154,  165,  159,  159,  162,  160,
      160,  166,  161,  161,  170,    0,  167,  164,  169,    0,
      168,    0,  163,  166,  164,  164,  165,  171,  162,  162,

      167,  168,  176,  169,  163,  163,  173,    0,  165,  165,
      170,    0,  172,  171,  166,  166,  174,  170,  170,  167,
      167,  169,  169,  168,  168,  172,  177,  173,  178,    0,
      171,  171,    0,  174,  179,  176,  176,  180,    0,  173,
      173,    0,  181,    0,  182,  172,  172,  179,  185,  174,
      174,  180,  184,  177,  178,  181,    0,  186,    0,  177,
      177,  178,  178,  182,    0,  184,  187,  179,  179,  186,
      180,  180,  185,    0,    0,  181,  181,  182,  182,  187,
        0,  185,  185,    0,    0,  184,  184,    0,    0,    0,
      186,  186,    0,    0,    0,    0,    0,    0,    0,  187,

      187,  190,    0,  190,  190,  190,  190,  190,  191,  191,
      191,  191,  191,  191,  191,  192,  192,    0,  192,  193,
      193,  194,    0,  194,  194,  195,  195,  195,  195,  195,
      195,  195,  196,    0,  196,  196,  197,  197,  197,  197,
      197,  197,  197,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex_analyzer.lex"
#define INITIAL 0
/* Analisador léxico - Leonardo Veiga, Pedro Accorsi e Rafaela Kreusch*/
/* Todo*/
/* Reconhecer "*(pt + i)"*/
/* Retirar o print do comentário de bloco*/
/* Retirar o print do comentário de linha*/
/* & = operador lógico*/
/* Ignorar o INCLUDE*/
/* Considerar ponteiro como operadr aritmético*/
#line 14 "lex_analyzer.lex"

#define MAX_VAR_LENGTH 30
#define MAX_VARS       100
#define MAX_CONTEXTS   15 

#include <math.h>
#include <stdbool.h>

//struct definition
typedef struct VariableIdentifier{
	char name[30];
	int id;
} varId;

typedef struct ContextIdentifier{
	varId variables[MAX_VARS];
} contextId;

enum ErrorIdentifier{
	var_overflow,
	var_length_overflow,
	context_overflow,
	context_underflow
} errorId;

//global var definition
int currentContext    = 0;
int idCounter         = 0 ;
bool isDeclaration    = false;
contextId allContexts[MAX_CONTEXTS];

//global func implementation
void initContexts(){
	for(int i=0; i<MAX_CONTEXTS; i++){
		for(int j=0; j<MAX_VARS; j++){
			allContexts[i].variables[j].name[0] = '\0';
			allContexts[i].variables[j].id      = -1;
		}
	}
}

void enterNewContext(){
	++currentContext;
	if(currentContext > MAX_CONTEXTS)
		FATAL_ERROR(context_overflow);
}

void leaveContext(){
	--currentContext;
	if(currentContext < 0)
		FATAL_ERROR(context_underflow);
}

void addVarToContext(char *varName, int varId){
	if(strlen(varName) > MAX_VAR_LENGTH)
		FATAL_ERROR(var_length_overflow);

	for(int i=0; i<MAX_VARS; i++){
		if( allContexts[currentContext].variables[i].id == -1 ){
			allContexts[currentContext].variables[i].id   = varId;
			strcpy(allContexts[currentContext].variables[i].name, varName);
			return;
		}
	}
	FATAL_ERROR(var_overflow);
}

void FATAL_ERROR( int error ){
	char errorMsg[500];
	switch(error){
		case var_overflow:        sprintf(errorMsg, "fatal variable error -- max number of variables (%d) per context reached", MAX_VARS)    ; break;
		case var_length_overflow: sprintf(errorMsg, "fatal variable error -- variable length greater than max allowed (%d) ", MAX_VAR_LENGTH); break;
		case context_overflow:    sprintf(errorMsg, "fatal context error -- max number of contexts (%d) reached", MAX_CONTEXTS)              ; break;
		case context_underflow:   sprintf(errorMsg, "fatal context error -- illegal attempt to leave unopened context")                      ; break;
	}
	(void) fprintf( stderr, "%s\n", errorMsg );
	exit( -1 );
}

int getId(char *varName){
	int varId = 0;
	if(isDeclaration){
		isDeclaration = false;
		varId = idCounter++;
		addVarToContext(varName, varId);
		return varId;
	}
	for(int i=currentContext; i >= 0; i-- ){ 
		for(int j=0; j<MAX_VARS; j++){
        	if(allContexts[i].variables[j].id == -1)
				break;
				 
			if(strcmp(varName, allContexts[i].variables[j].name) == 0)
				return allContexts[i].variables[j].id;
			
		}
		
	}
	varId = idCounter++;
	addVarToContext(varName, varId);
	return varId;
}

char * cropEndOfLine(char * text){
	int len = strlen(yytext);
	if( yytext[len-1] == '\n')
		yytext[len-1] = 0;
	return yytext;
}

#line 747 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 150 "lex_analyzer.lex"


#line 901 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 190 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 844 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 152 "lex_analyzer.lex"

	YY_BREAK
case 2:
YY_RULE_SETUP
#line 153 "lex_analyzer.lex"

	YY_BREAK
case 3:
YY_RULE_SETUP
#line 154 "lex_analyzer.lex"
{ isDeclaration = true; printf("[reserved_word, %s]", yytext)                ;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 155 "lex_analyzer.lex"
{ printf("[reserved_word, %s]"                      , yytext)                ;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 156 "lex_analyzer.lex"
{ printf("[Expressao nao identificada: %s (%d)]"    , yytext, atoi(yytext))  ;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 157 "lex_analyzer.lex"
{ printf("[num, %d]"                                , atoi(yytext))          ;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 158 "lex_analyzer.lex"
{ printf("[num, %s]"                                , yytext)                ;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 159 "lex_analyzer.lex"
{ printf("[id, %d,  %s]"                                , getId(yytext), yytext) ;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 160 "lex_analyzer.lex"
{ printf("[[string_literal, %s]"                    , yytext)                ;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 161 "lex_analyzer.lex"
{ printf("[Relational_Op, %s]"                      , yytext)                ;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 162 "lex_analyzer.lex"
{ printf("[Arith_Op, %s]"                           , yytext)                ;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 163 "lex_analyzer.lex"
{ printf("[Attrib_Op, %s]"                          , yytext)                ;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 164 "lex_analyzer.lex"
{ printf("[l_paren, %s]"                            , yytext)                ;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 165 "lex_analyzer.lex"
{ printf("[r_paren, %s]"                            , yytext)                ;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 166 "lex_analyzer.lex"
{ enterNewContext(); printf("[l_braces, %s]"        , yytext)                ;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 167 "lex_analyzer.lex"
{ leaveContext();    printf("[r_braces, %s]"        , yytext)                ;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 168 "lex_analyzer.lex"
{ printf("[comma, %s]"                              , yytext)                ;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 169 "lex_analyzer.lex"
{ printf("[semicolon, %s]"                          , yytext)                ;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 170 "lex_analyzer.lex"
{ printf("[l_bracket, %s]"                          , yytext)                ;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 171 "lex_analyzer.lex"
{ printf("[l_bracket, %s]"                          , yytext)                ;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 172 "lex_analyzer.lex"
{ printf("[logic_op,  %s]"                          , yytext)                ;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 173 "lex_analyzer.lex"

	YY_BREAK
case 23:
YY_RULE_SETUP
#line 174 "lex_analyzer.lex"

	YY_BREAK
case 24:
YY_RULE_SETUP
#line 176 "lex_analyzer.lex"
ECHO;
	YY_BREAK
#line 1104 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 190 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 190 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 189);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 176 "lex_analyzer.lex"


int main(int argc, char *argv[]){
	initContexts();
	yyin = fopen(argv[1], "r");
	yylex();
	fclose(yyin);
	return 0;
}